#!/usr/bin/perl

use diagnostics;

sub lit {
    my $txt= `cat comscore.dir/$_[0]`;
    chomp $txt;
    return $txt;
}

print <<___
gannett_ut.add_loader(function(gdata) {
console.log('comscore loader');
udm_('http' + (document.location.href.charAt(4) == 's' ? 's://sb' : '://b') + '.scorecardresearch.com/b?' + ["c1=2", "c2=@{[lit 'account']}", "name="+@{[lit 'name']}, "comscorekw="+@{[lit 'comscorekw']}, "category="+@{[lit 'category']}, "templatetype="+@{[lit 'templatetype']}].join('&'));
});
___
